### ISSUE TITLE
[question] How to choose initial parameters?

### ISSUE THREAD

**Issue by robinparisi** [vijayee/cuckoo-filter#1]
Hi,

I'm discovering cuckoo filter and I'm not sure about the method to choose size, bucket size and finger print size?

I've found this link related to bloom filter (https://krisives.github.io/bloom-calculator/) but can't find any clear ressource for cuckoo and  :/

BTW, there is a small error in the readme (line 2, ScalableFilter should be ScalableCuckooFilter).

**Comment by vijayee** [comment]
@robinparisi Thanks for the question. I don't have a calculator for you I may have to create one. I typically size my buckets and fingerprints at 4 bytes and 4 buckets . This should be enough to hold billions of records without collision. This is what was used in the research paper that defined the algorithm. You could use smaller sizes if you data set is tiny.

**Comment by robinparisi** [comment]
@vijayee Oops, I forgot to close this one. Thanks for the response!
